source "http://rubygems.org"
gem "nokogiri"
gem "rack", "~>1.1"
gem "rails", "2.3.8"
gem "radiant", "0.9.1"
gem "capistrano"
gem "capistrano-deepmodules"
gem "rack-test"
gem "fastercsv"
gem "spreadsheet"
